### ISSUE TITLE
Qt6 builds are broken because of sip discrepency

### ISSUE THREAD

**Issue by denisri** [brainvisa/aims-free#102]
After 96add67e7b201c326f5e2f88372dbbd85747f4cd, pyaims builds are broken with errors like:
```
sip-build: /casa/host/build/share/aims-5.2/sip/rcobject.sip: line 253: column 3: 'carto::RCObject::__hash__' must return a Py_hash_t
```
The commit above has precisely replaced `Py_hash_t` with `long`, which seems to be the contrary to what is expected.
I am building using sip 6.7.9. The change was done to build in conda, supposedly using the same sip 6.7.9.
But inside the pyaims module in conda, `hex(aims.sip_module_version())` tells `0x60602` and not `0x060709` as expected (`sip-build -V` actually prints `6.7.9`  in the conda environment). Is it possible that there has been a sip versions mixup ?
Anyway I don't know when this `Py_hash_t` requirement has emerged, it is possibly in sip 6.7.
So we should revert the commit 96add67e7b201c326f5e2f88372dbbd85747f4cd, but change the test in `system.tpl`:
```
%#if SIP_VERSION < 0x060000%

typedef long Py_hash_t;
typedef int Py_ssize_t;

%#endif%
```
to:
```
%#if SIP_VERSION < 0x060700%
[...]
```

**Comment by sapetnioc** [comment]
I do not know if it is related with the two sip veriosn but there are two sip packages installed in the environment:

```
$ mamba list | grep sip
pyqt5-sip                 12.11.0         py310heca2aa9_3    conda-forge
sip                       6.7.9           py310hc6cd4ac_0    conda-forge

```

Uninstallation of `pyqt5-sip` would remove many dependencies including `sip` itself:

```
$ mamba uninstall pyqt5-sip
...
────────────────────────────────────────────────────────────────────
  Remove:
────────────────────────────────────────────────────────────────────

  - matplotlib        3.4.3  py310hff52083_2  conda-forge         
  - ply                3.11  py_1             conda-forge         
  - pyqt             5.15.7  py310hab646b1_3  conda-forge         
  - pyqt5-sip       12.11.0  py310heca2aa9_3  conda-forge         
  - qtconsole         5.4.3  pyhd8ed1ab_0     conda-forge         
  - qtconsole-base    5.4.3  pyha770c72_0     conda-forge         
  - qtpy              2.3.1  pyhd8ed1ab_0     conda-forge         
  - sip               6.7.9  py310hc6cd4ac_0  conda-forge         
  - toml             0.10.2  pyhd8ed1ab_0     conda-forge         

  Summary:

  Remove: 9 packages
```

I do not know how to see what files are installed by a package.

**Comment by denisri** [comment]
Strange. Apparently `pyqt5-sip` was built using an earler sip 6.6.2, and the `sip` package provides sip 6.7.9, which is somewhat inconsistent, but perhaps follow the same ABI.
I'll try the fix I propose, and we'll see if it breaks your conda builds or not...

**Comment by denisri** [comment]
I have pushed the change, and it fixes the build for me. Could you test it in a conda build when you have time please ?

**Comment by sapetnioc** [comment]
Well, no. The compilation fail with the error:

```
sip-build: /home/yann/casaconda/build/share/aims-5.2/sip/system_VOID.sip: line 62: column 14: 'Py_hash_t' is unexpected
Error: sip exited with signal 1
```

I have seen [here](https://www.riverbankcomputing.com/news/SIP_v6.0.0_Released) that the ABI version could be involved in the definition of `Py_hash_t`. Is it possible to test this ABI version instead of SIP version ? If not, could we define something like an environment variable to use it in a test and force a behavior ?

**Comment by sapetnioc** [comment]
I think that `SIP_API_MAJOR_NR` (found in sip doc) or `SIP_ABI_MAJOR_VERSION` (not in sip documentation) may contain the ABI version. I made a research in the Conda directory and found a `sip.h.in` file containing:
```
/* The version of the ABI. */
#define SIP_ABI_MAJOR_VERSION       12
#define SIP_ABI_MINOR_VERSION       12
#define SIP_MODULE_PATCH_VERSION    1

...

/* Support the historical names. */
#define SIP_API_MAJOR_NR    SIP_ABI_MAJOR_VERSION
#define SIP_API_MINOR_NR    SIP_ABI_MINOR_VERSION
```

**Comment by denisri** [comment]
Whew. So PyQt5 in conda is built using sip6 but still ABI 12.
`SIP_VERSION` in our preprocessor is passed explicitly, we can consider passing also `SIP_ABI_*` or/and `SIP_API_*`, but then I'm not sure how `sip-build` generates its C++ source code. It has not option to select the ABI version so I don't understand why / how it produces code for ABI 12 in conda while it uses ABI 13 in another environment ? Other tools like `sip-module` (which actually writes a `sip.h` file) have an option `--abi-version`, but `sip-build` which generates the C++ code from `.sip` files does not.
I have already spent some time playing around (well, "playing" is a bit exagerated...) with the input project specs for sip-build, it has a [sip-abi](https://www.riverbankcomputing.com/static/Docs/sip/pyproject_toml.html#tool-sip-project-section) option, but if I understand it is not a way to force it to use a specific ABI, but just a "minimum version" which says that the input `.sip` code is meant for a minimum ABI version (?). Anyway it doesn't work for forcing the code generation, and I haven't found a way to do so.
However here `sip-build` seems to be already tuned to produce ABI 12 and not 13, I don't know how...
Well, anyway I can modify the tools on our side but I feel a bit puzzled about all that...

**Comment by sapetnioc** [comment]
The problem is a bit more complex. On Conda, `Py_hash_t` is defined but using it as `__hash__` return type raises an error:
```
sip-build: /home/yann/casaconda/build/share/aims-5.2/sip/rcobject.sip: line 253: column 3: 'carto::RCObject::__hash__' must return a long
/home/yann/casaconda/build/share/aims-5.2/sip/genericobject.sip: line 106: column 3: 'carto::GenericObject::__hash__' must return a long
/home/yann/casaconda/build/share/aims-5.2/sip/rcptr_GenericObject.sip: line 211: column 3: 'rc_ptr_GenericObject::__hash__' must return a long
/home/yann/casaconda/build/share/aims-5.2/sip/rcptr_Tree.sip: line 211: column 3: 'rc_ptr_Tree::__hash__' must return a long
/home/yann/casaconda/build/share/aims-5.2/sip/rcptr_Graph.sip: line 208: column 3: 'rc_ptr_Graph::__hash__' must return a long
/home/yann/casaconda/build/share/aims-5.2/sip/rcptr_Vertex.sip: line 208: column 3: 'rc_ptr_Vertex::__hash__' must return a long
/home/yann/casaconda/build/share/aims-5.2/sip/rcptr_Edge.sip: line 208: column 3: 'rc_ptr_Edge::__hash__' must return a long
/home/yann/casaconda/build/share/aims-5.2/sip/rcptr_DataSource.sip: line 220: column 3: 'rc_ptr_DataSource::__hash__' must return a long
...
/```

**Comment by sapetnioc** [comment]
I have an idea of a workaround that may work on both environments. Use `Aims_hash_t` instead of `Py_hash_t` and define it that way:

```
%#if SIP_VERSION < 0x060000%
typedef long Py_hash_t;
typedef int Py_ssize_t;
%#endif%

%#if SIP_ABI_MAJOR_VERSION < 12%
typedef long Aims_hash_t;
%#else%
typedef Py_hash_t Aims_hash_t;
%#endif%
```

Right now it does not compile, I have to find what to include so that `Aims_hash_t` is available in other `*.sip` or `*.tpl` codes.

**Comment by denisri** [comment]
So in ABI 12 `Py_hash_t` is defined but `__hash__` mustn't return a `Py_hash_t` ??? That's crazy !....
The problem here is to pass `SIP_ABI_MAJOR_VERSION` to the preprocessor which interprets the line
```
%#if SIP_ABI_MAJOR_VERSION < 12%
```
I'm making a modif in this way.

By the way can you check that, in your conda build tree, in the `CMakaCache.txt` file, the variable `SIP_ABI` has a value with 12 or 12.something ?

**Comment by sapetnioc** [comment]
Yes, it does:
```
//SIP ABI version
SIP_ABI:STRING=12.11
```

**Comment by sapetnioc** [comment]
Thank you for the modif because my sip knowledge does not allow me to make an elegant fix. I could have finished copying `Aims_hash_t` definition in the few `*.tpl` files that use it.

**Comment by denisri** [comment]
OK. Are you certain `Py_hash_t` is actually defined in ABI 12 ? Do we really need to use another type name `Aims_hash_t` ?

**Comment by sapetnioc** [comment]
Almost certain because the typedef cannot be defined and the error when using it is "must return a long".
The (very strange) problem is that in some cases we must une `Py_hash_t` and in other cases we musn't. A new type is not mandatory, a `%#if ...%` could be used where `Py_hash_t` is used (only a few occurrences).

**Comment by sapetnioc** [comment]
I think it may be a PyQt bug. `Py_hash_t` must be defined testing only the sip version but not the ABI version.

**Comment by denisri** [comment]
> Almost certain because the typedef cannot be defined and the error when using it is "must return a long". The (very strange) problem is that in some cases we must une `Py_hash_t` and in other cases we musn't. A new type is not mandatory, a `%#if ...%` could be used where `Py_hash_t` is used (only a few occurrences).

The `%#if ...%` syntax is only valid in `.tpl` files which are preprocessed to generate `.sip` files (this is our internal cuisine). `__hash__` is found in `.sip` files which are not all `.tpl` files. Well we could move them to preprocessed files, but it's a bit overkill. In that case the additional type makes more sense for me.

**Comment by sapetnioc** [comment]
I see. This code is too old otherwise templates would have probably been in Jinja2 and I may have been able to help more.

**Comment by denisri** [comment]
OK I have pushed modifs to pass `SIP_ABI_MAJOR_VERSION` to `.tpl` preprocesing.
I have also pushed an attempt to defiine `Aims_hash_t` in `system.tpl` and used it in `rcobject.sip` just to check if it works. It builds OK in my sip6/qt6 build tree. If it's OK for you we will replace `Py_hash_t` with `Aims_hash_t` everywhere.

**Comment by sapetnioc** [comment]
I still have errors where `Py_hash_t` is used but I do not see others when building `aims-free`

**Comment by denisri** [comment]
If errors are only on `Py_hash_t`, then maybe it's OK with `Aims_hash_t`. Can you try replacing them ?

**Comment by sapetnioc** [comment]
Much better. I quickly submmitted before end of compilation. I have to go for about 1 hour. I saw this error:
```
[100%] Building CXX object build_files/aims-free/pyaims/pyaimsalgo/src/sip/CMakeFiles/aimsalgosip.dir/sipbuild/aimsalgosip/sipaimsalgosippart0.cpp.o
/home/yann/casaconda/build/share/aims-5.2/sip/masklinresampler.sip:14:17: warning: 'template<class T> class aims::MaskLinearResampler' is deprecated [-Wdeprecated-declarations]
   14 |   typedef aims::MaskLinearResampler<int16_t> MaskLinearResampler_S16;
      |                 ^~~~~~~~~~~~~~~~~~~
In file included from /home/yann/casaconda/build/share/aims-5.2/sip/masklinresampler.sip:5:
/home/yann/casaconda/build/include/aims/resampling/masklinresampler.h:66:3: note: declared here
   66 |   MaskLinearResampler : public Resampler< T >
      |   ^~~~~~~~~~~~~~~~~~~
/home/yann/casaconda/build/build_files/aims-free/pyaims/pyaimsalgo/src/sip/sipbuild/aimsalgosip/sipaimsalgosippart0.cpp: In function 'long int slot_rc_ptr_GeometricProperties___hash__(PyObject*)':
/home/yann/casaconda/build/build_files/aims-free/pyaims/pyaimsalgo/src/sip/sipbuild/aimsalgosip/sipaimsalgosippart0.cpp:12249:16: error: '::Aims_hash_t' has not been declared
12249 |                 return SIP_NULLPTR;
      |                ^~~~~~~~~~~
/home/yann/casaconda/build/share/aims-5.2/sip/rcptr_GeometricProperties.sip:222:3: error: 'sipRes' was not declared in this scope
  222 |   sipRes =
      |   ^~~~~~
/home/yann/casaconda/build/build_files/aims-free/pyaims/pyaimsalgo/src/sip/sipbuild/aimsalgosip/sipaimsalgosippart0.cpp: In function 'long int slot_rc_ptr_TrilinearFfd___hash__(PyObject*)':
/home/yann/casaconda/build/build_files/aims-free/pyaims/pyaimsalgo/src/sip/sipbuild/aimsalgosip/sipaimsalgosippart0.cpp:12976:16: error: '::Aims_hash_t' has not been declared
12976 | 
      |                ^          
/home/yann/casaconda/build/share/aims-5.2/sip/rcptr_TrilinearFfd.sip:222:3: error: 'sipRes' was not declared in this scope
  222 |   sipRes =
      |   ^~~~~~
/home/yann/casaconda/build/build_files/aims-free/pyaims/pyaimsalgo/src/sip/sipbuild/aimsalgosip/sipaimsalgosippart0.cpp: In function 'long int slot_rc_ptr_SplineFfd___hash__(PyObject*)':
/home/yann/casaconda/build/build_files/aims-free/pyaims/pyaimsalgo/src/sip/sipbuild/aimsalgosip/sipaimsalgosippart0.cpp:13703:16: error: '::Aims_hash_t' has not been declared
13703 | extern "C" {static PyObject *slot_rc_ptr_SplineFfd___eq__(PyObject *,PyObject *);}
      |                ^~~~~~~~~~~
/home/yann/casaconda/build/share/aims-5.2/sip/rcptr_SplineFfd.sip:222:3: error: 'sipRes' was not declared in this scope
  222 |   sipRes =
      |   ^~~~~~
/home/yann/casaconda/build/build_files/aims-free/pyaims/pyaimsalgo/src/sip/sipbuild/aimsalgosip/sipaimsalgosippart0.cpp: In function 'long int slot_rc_ptr_FfdTransformation___hash__(PyObject*)':
/home/yann/casaconda/build/build_files/aims-free/pyaims/pyaimsalgo/src/sip/sipbuild/aimsalgosip/sipaimsalgosippart0.cpp:14431:16: error: '::Aims_hash_t' has not been declared
14431 | 
      |                ^          
/home/yann/casaconda/build/share/aims-5.2/sip/rcptr_FfdTransformation.sip:222:3: error: 'sipRes' was not declared in this scope
  222 |   sipRes =
      |   ^~~~~~
make[2]: *** [build_files/aims-free/pyaims/pyaimsalgo/src/sip/CMakeFiles/aimsalgosip.dir/build.make:1191 : build_files/aims-free/pyaims/pyaimsalgo/src/sip/CMakeFiles/aimsalgosip.dir/sipbuild/aimsalgosip/sipaimsalgosippart0.cpp.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:23746 : build_files/aims-free/pyaims/pyaimsalgo/src/sip/CMakeFiles/aimsalgosip.dir/all] Erreur 2
make: *** [Makefile:166 : all] Erreur 2
```

**Comment by denisri** [comment]
`sipRes` not declared in a `%MethodCode` ??? How is it possible ? This variable is defined in the sip infrastructure...

**Comment by denisri** [comment]
Ah OK the problem is just that `Aims_hash_t` is not defined on C++ side in pyaimsalgo and other bindings. I can fix that.

**Comment by denisri** [comment]
OK, can you try again please ?

**Comment by sapetnioc** [comment]
It's all good for me ! Great !

**Comment by denisri** [comment]
OK ! :)
