### ISSUE TITLE
The .minf file associated with a Graph is ignored by AIMS

### ISSUE THREAD

**Issue by ylep** [brainvisa/aims-free#15]
AIMS completely ignores a `.minf` file associated with a `.arg` file (a `Graph`). This is a problem when Graphs are used in Axon, because Axon stores attributes in the `.minf` file (notably `referential`).

As a result of this bug, these attributes are not inherited by derived Graphs.

**Comment by denisri** [comment]
fixed by b4009a01b6a95991fd5de61f504d853b65c26bb1

**Comment by jongheon33** [comment]
@ylep salut, Yann Leprince, je suis le doctorant en sociologie qui ai fait un entretien avec toi, et je suis vraiment désolé de te contacter comme cela, mais je n'ai pas d'autre moyen. Je n'ai pas noté ton mail et les autres adresses que j'avais ne sont probablement plus utilisées... Si tu vois ce message, peux-tu m'envoyer un mail à jongheon.kim@unil.ch, s'il te plaît? J'effacerai ce message dans quelques jours...
