### ISSUE TITLE
read method fails to read volume with borders

### ISSUE THREAD

**Issue by nsouedet** [brainvisa/aims-free#17]
The following code fails to properly read volume with borders
`
//--- std --------------------------------------------------------------------
#include <iostream>
#include <fstream>
//--- aims -------------------------------------------------------------------
#include <aims/rgb/rgb.h>
//#include <aims/io/io_g.h>
#include <aims/io/writer.h>
#include <aims/io/reader.h>
#include <aims/io/finder.h>
//--- cartodata --------------------------------------------------------------
#include <cartodata/volume/volume.h>
//--- cartobase --------------------------------------------------------------
#include <cartobase/exception/file.h>
#include <cartobase/stream/fileutil.h>
#include <cartobase/config/verbose.h>
//----------------------------------------------------------------------------
using namespace std;
using namespace carto;
using namespace aims;

int main( int argc, const char **argv )
{
    carto::verbose = 1;
    carto::debugMessageLevel = 100;
    std::string image_uri = "Slide91_test_1000x1000.ima?sx=273&sy=273&bx=136&by=136&bz=136";

    typedef AimsRGBA VoxelType;
    carto::VolumeRef<VoxelType> dataIn;
    Reader<carto::VolumeRef<VoxelType> > reader(image_uri);
    reader.read(dataIn);
    
    Writer<carto::VolumeRef<VoxelType> > writer("/tmp/test_write_rgba_ko.ima");
    writer.write(dataIn);

    writer.setFileName("/tmp/test_write_rgba_refvol_ko.ima");
    writer.write(dataIn.refVolume());
    return 0;
}
`

whereas following code is successful
`
//--- std --------------------------------------------------------------------
#include <iostream>
#include <fstream>
//--- aims -------------------------------------------------------------------
#include <aims/rgb/rgb.h>
//#include <aims/io/io_g.h>
#include <aims/io/writer.h>
#include <aims/io/reader.h>
#include <aims/io/finder.h>
//--- cartodata --------------------------------------------------------------
#include <cartodata/volume/volume.h>
//--- cartobase --------------------------------------------------------------
#include <cartobase/exception/file.h>
#include <cartobase/stream/fileutil.h>
#include <cartobase/config/verbose.h>
//----------------------------------------------------------------------------
using namespace std;
using namespace carto;
using namespace aims;

int main( int argc, const char **argv )
{
    carto::verbose = 1;
    carto::debugMessageLevel = 100;
    std::string image_uri = "Slide91_test_1000x1000.ima?sx=273&sy=273&bx=136&by=136&bz=136";

    typedef AimsRGBA VoxelType;
    carto::VolumeRef<VoxelType> dataIn;
    Reader<carto::Volume<VoxelType> > reader(image_uri);
    dataIn = reader.read();
    
    Writer<carto::VolumeRef<VoxelType> > writer("/tmp/test_write_rgba_ok.ima");
    writer.write(dataIn);

    writer.setFileName("/tmp/test_write_rgba_refvol_ok.ima");
    writer.write(dataIn.refVolume());
    return 0;
}

differences come from the 2 different called read method. The 2 refVolume are correct, but I think that _blitz array is not reset properly. 
`

[Slide91_test_1000x1000.ima.zip](https://github.com/brainvisa/aims-free/files/2690083/Slide91_test_1000x1000.ima.zip)

**Comment by denisri** [comment]
I have dug into the IO code, and it turns out that the problem is actually even lower level than the IO system: it is actually in the copy of the buffer block inside a volume, which is made by default by actually copying the block (memory allocation) instead of duplicating the allocation strategy of the original volume.
So I think I can fix it, and anyway it happens because there is an actual volume copy in the IO code, which is largely sub-optimal. I can try to improve it also.
