### ISSUE TITLE
Issue with None in soma aims 

### ISSUE THREAD

**Issue by manuegrx** [brainvisa/aims-free#35]
Hi, 

Following  the adaptation to python 3  I am currently testing some part of  the catidb3_client project and I have an issue with soma in this part of the code: 
``` 
from soma import aims
fp = os.path.join(cati_push_zone_dir, value) 
header = None
try: 
    f = aims.Finder()
    f.check(fp)
    header = f.header()
except:
    errors.append((parameter, 'Image cannot be read ' 'by aims: %s\n%s' % (fp,''.join(traceback.format_exception(*sys.exc_info())).strip())))
if header:
    if value.endswith(".nii.gz"):
        data_type = header['data_type']
        [...]
        dimension = (tuple(header['volume_dimension']) + (1, 1, 1))[:4] 
``` 
Sometime header is `None` (type `class 'soma.aims.Object'` ) (because fp is not a nifti image but a dicom in tar.gz) and in this case I have the following error: 
``` 
File "/casa/src/catidb3_client/bug_fix/python/catidb_api/shared_actions/mri_3dt1.py", line 297, in check_action_img_files\n    
if header:\n  File "/casa/build/python/soma/aims/__init__.py", line 641, in proxylen\n    raise TypeError("object of type \'Object\' has no len()")\nTypeError: object of type \'Object\' has no len()\n'
```
I also tried to change `if header`by `if header is not know` but in this case it goes in the loop and so I have a bug at `dimension = (tuple(header['volume_dimension']) ` 

In python 2, there was no problem. 

Emmanuelle

**Comment by sapetnioc** [comment]
I think the methods used to convert an object to a boolean may have changed in Python 3. This would explain the different behavior.

I wonder if the result of `check()` indicates read failure. If yes, you should get a header only if the result is `True`. But `header` is a Aims object. Therefore, it has a `isNull()` method and a `isNone()` method. I do not know if they are equivalent but it is worth to try them in your `if`.
