### ISSUE TITLE
Installation compiling issues (Ubuntu 20.04)

### ISSUE THREAD

**Issue by andrewrgarcia** [brainvisa/aims-free#37]
After running cmake, I get the following message:

By not providing "Findbrainvisa-cmake.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "brainvisa-cmake", but CMake did not find one.

  Could not find a package configuration file provided by "brainvisa-cmake"
  with any of the following names:

    brainvisa-cmakeConfig.cmake
    brainvisa-cmake-config.cmake

  Add the installation prefix of "brainvisa-cmake" to CMAKE_PREFIX_PATH or
  set "brainvisa-cmake_DIR" to a directory containing one of the above files.
  If "brainvisa-cmake" provides a separate development package or SDK, be
  sure it has been installed.

I am running Ubuntu 20.04 . Please help
-Andrew

**Comment by denisri** [comment]
AIMS is part of a large projects set, and has sub-components and dependencies over other components. CMake is not designed for this "multiple projects" structure, thus we had to write a build tool to handle this. The tool is using cmake but provides additional features and cmake modules.
The easiest way to build nowadays is to use a containerized development environment: [casa-distro](https://github.com/brainvisa/casa-distro) which provides containers with all the required development tools and libraries, in a system which has been tested for that.
If the containerized build does not suit you, it is possible to build without it, using the build tools [brainvisa-cmake](https://github.com/brainvisa/brainvisa-cmake) and its command `bv_maker`. But note that we have not tried compiling on Ubuntu 20.04 yet and it's possible that there would be a few problems with some system libraries (for instance on Ubuntu 18.04 we discovered a bug in the sip/PyQt libs which required to install another version). Note also that there are a number of dependencies to be installed first.
For these reasons we strongly recommend the containerized version, using [casa-distro](https://github.com/brainvisa/casa-distro).

Now if you only need to run the programs and not develop using the libraries, [installing binaries](http://brainvisa.info/web/download.html) is much easier.
