### ISSUE TITLE
running aims outside of brainvisa

### ISSUE THREAD

**Issue by octlie** [brainvisa/aims-free#44]
Dear All, 

Is there a way to run Aims outside of Brainvisa? Meaning, using python only (pyaims) and perhaps some 'hacked' (individual) functions related to aims from Brainvisa? I want to run a limited code portion from a Brainvisa function referencing the Aims library (actually from Intranat electrodes package), can I install aims by itself on windows and run it? If so, please assist with install steps, thank you, Octavian

**Comment by sapetnioc** [comment]
Yes, many Aims objects and functions have been connected to Python. You can find more information on http://brainvisa.info/pyaims/sphinx/index.html

We are about to release a new major version of BrainVISA. You can use it on Windows but we had to stop providing a native Windows version. You will have to use a virtualization technology, either a container or a virtual machine.

If you want to try the new BrainVISA immediately, you can have a look at our [future installation instructions](https://new.brainvisa.info/web/download.html). But be warned that the page content as well as the packages will be modified before the release.
