### ISSUE TITLE
build failed : "bucket_util.sip" missing

### ISSUE THREAD

**Issue by clarafischer** [brainvisa/aims-free#48]
Hello, I try to install a new casa_distro (distro cati_platform) on my laptop and I can not finish the build, it stop in the aimssippart and says that :
[ 48%] Generating sipaimssippart0.cpp, sipaimssippart1.cpp, sipaimssippart2.cpp, sipaimssippart3.cpp, sipaimssippart4.cpp, sipaimssippart5.cpp, sipaimssippart6.cpp, sipaimssippart7.cpp, sipaimssippart8.cpp, sipaimssippart9.cpp, sipaimssippart10.cpp, sipaimssippart11.cpp, sipaimssippart12.cpp, sipaimssippart13.cpp, sipaimssippart14.cpp, sipaimssippart15.cpp

sip: Unable to find file "bucket_util.sip"
Error: sip exited with signal 1
build_files/aims-free/pyaims/src/sip/CMakeFiles/aimssip.dir/build.make:1605: recipe for target 'build_files/aims-free/pyaims/src/sip/sipaimssippart0.cpp' failed
make[2]: *** [build_files/aims-free/pyaims/src/sip/sipaimssippart0.cpp] Error 1
CMakeFiles/Makefile2:46129: recipe for target 'build_files/aims-free/pyaims/src/sip/CMakeFiles/aimssip.dir/all' failed
make[1]: *** [build_files/aims-free/pyaims/src/sip/CMakeFiles/aimssip.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

Any ideas ? Thank you for your help !
Clara

**Comment by denisri** [comment]
Oh you're right, this file was forgotten (I didn't see it in the list of files not under git ;) ). I'm fixing it in a couple of seconds.

**Comment by clarafischer** [comment]
Great ! Thank you very much for this quick debug !
