### ISSUE TITLE
numpy.asarray method fails on soma.aims.Volume when specifing a dtype parameter

### ISSUE THREAD

**Issue by nsouedet** [brainvisa/aims-free#49]
Here is a code to reproduce the issue :
```python
import numpy as np
from soma import aims
vol = aims.Volume(dtype='int16')
np.asarray(vol , dtype=np.int32)
```
It leads to the error
`
TypeError: Volume_S16.__array__(): too many arguments
`

As a consequence, it is necessary to do np.asarray(np.asarray(vol) , dtype=np.int32) to obtain a numpy array with the new data type.

**Comment by denisri** [comment]
Crap. I was even not aware of these optional arguments (`dtype` and also `order`). So numpy requires to explicitly handle data type conversion and array ordering in array access functions (`something.__array__()`) where it could do it by its own and we cannot handle it easily in every object type we bind to numpy (vectors, textures etc) :/
We could maybe patch the `__array__` methods when they have only one argument... ? but this seems kind of useless work when `numpy asarray()` could have simply called `something.__array().astype(dtype=dtype, order=order, copy=False)`. Grmbl...
