### ISSUE TITLE
Add new function to build a view in a volume that only exposes unread borders

### ISSUE THREAD

**Issue by nsouedet** [brainvisa/aims-free#54]
While partialy reading a volume with borders, the reader fills borders with image value whenever it is possible (i.e. when borders are inside the domain of the global image).
Sometimes we need to also fill borders that are outside the domain of the global image. Today the class aims::BorderFiller is implemented and allows to fill the border of a VolumeRef regardless it was previously filled during read.
The idea here is to be able to fill borders only when they are outside the domain of the global image.
We following function build a view only with borders that were not filled during partial reading.
Once the view is created it is possible to use the standard methods of aims::BorderFiller on it.
My question is: "how and where should we integrate this function named buildUnfilledBorderView in aims ?"
I propose to add "buildUnfilledBorderView" as a static method of the aims::BorderFiller class. Moreover, we could add a parameter "onlyUnread" to methods:
aims::BorderFiller::fillConstant
aims::BorderFiller::fillMedian
aims::BorderFiller::fillNearest
aims::BorderFiller::fillMirror

When the "onlyUnread" parameter is set to true, the buildUnfilledBorderView method is called before filling the borders.
Are these mechanisms and namings OK for you ?

```c++
template<class T>
carto::VolumeRef<T> buildUnfilledBorderView(const carto::VolumeRef<T> & vol){
    if (!vol.isNull()) {
        const carto::VolumeRef<T> parent1 = vol.refVolume();
        if (!parent1.isNull()
            && parent1.allocatorContext().isAllocated()) {
            const carto::VolumeRef<T> parent2 = parent1.refVolume();
            if (!parent2.isNull() 
                && !parent2.allocatorContext().isAllocated()) {
                typedef typename carto::Volume<T>::Position Position;
                Position pos = vol.posInRefVolume().toVector();
                Position pos1 = parent1.posInRefVolume().toVector();
                Position pos2 = parent2.posInRefVolume().toVector();
                Position size = vol.getSize();
                Position size1 = parent1.getSize();
                Position size2 = parent2.getSize();
            
                size_t dims = pos.size();
            
                for(size_t d=0; d<dims; ++d) {
                    pos[d] = max(pos1[d], 0) - pos1[d];
                    size[d] = min(size1[d], size2[d] - pos1[d]) - pos[d];
                }
                
                return carto::VolumeRef<T>(vol.refVolume(), pos, size);
            }
        }
    }
    
    return vol;
}
 ```

**Comment by denisri** [comment]
I roughly understand the idea, and I agree, but I don't catch the the details yet...
This is a 3-level volume (a "border" and 2 views in it), right ? The larger one is the border (`parent2`), then a view contains the (partly) read file (`parent1`), then a 2nd view inside it is the view we are working on (`vol`) ?
Thus here we want to fill the border in `parent2` outside `parent1` (in other words, fillBorders on `parent1`=, is that is ? It seems more complex than that so I guess I'm missing something... And so I don't understand why you return a view from `parent1` and not from `parent2` ?

**Comment by nsouedet** [comment]
Yes it is a3-level volume, but in this case we have a partially read volume with borders. 
So the larger (parent2) one is **unallocated** and correspond to the global volume (not completely read).
The second one (parent1) is the allocated volume with borders (it was allocated by the reader and part of the border was filled when it was in the global image domain). 
The third one (vol) is the view we are working on.
The newly built view does not need vol as a parent, because it is also a view on the allocated volume with borders only where reader not filled it.

**Comment by denisri** [comment]
OK I get it, I missed the unallocated state of parent2. And here parent1 extends outside of parent1, OK OK...
Well, this seems OK to me...
