### ISSUE TITLE
Missing includes dependency in Makefiles

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/aims-free#58]
When compiling a new project without parallelism (i.e. with option `-j1`), we get the following error

```
[ 46%] Building CXX object build_files/aims-free/cartodata/src/cartogis/CMakeFiles/cartogis.dir/plugin/gisplugin.cc.o
/casa/src/aims/aims-free/master/cartodata/src/cartogis/plugin/gisplugin.cc:517:10: fatal error: aims/io/asciidatasourcetraits_aims.h: No such file or directory
 #include <aims/io/asciidatasourcetraits_aims.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
build_files/aims-free/cartodata/src/cartogis/CMakeFiles/cartogis.dir/build.make:62: recipe for target 'build_files/aims-free/cartodata/src/cartogis/CMakeFiles/cartogis.dir/plugin/gisplugin.cc.o' failed
```

Running `make -k` ignore the error and then generate the missing symlink for the include. Following builds are working.

**Comment by sapetnioc** [comment]
I see the missing file ins sources and in CMakeLists.txt. But in my `build/include` directory, the symlink is `cartobase/io/asciidatasourcetraits_aims.h`. Is the include line wrong or is there an error in my (brain new) compilation ?

**Comment by sapetnioc** [comment]
Sorry, I was wrong. There is no link to `asciidatasourcetraits_aims.h` (there is one in cartobase to `asciidatasourcetraits.h`). In fact, there is nothing except `config.h` in `include/aims`. I am trying to run `make -k` (I am compiling with `-j1`) because I suspect a make dependency problem here.

**Comment by sapetnioc** [comment]
This is it. The symlink was generated (as well as many other include symlinks) after the compilation. After `make -k` the problem is gone. We probably see the error only in non parallel compilation when include symlinks are not existing.

**Comment by sapetnioc** [comment]
A way to reproduce the problem with Singularity build :
```
cd /casa/host/build
rm -Rf include/aims/io
make
```

**Comment by sapetnioc** [comment]
I updated the ticket name and description.

**Comment by denisri** [comment]
It's a dependency problem: the file is in `aimsdata` (subdirectory of `aims-free` component), but it is used from `cartodata/cartogis` (another subdirectory of `aims-free`, but which is normally independent from `aimsdata` and upstream from it).
`asciidatasourcetraits_aims.h` actually only needs `vector.h`, which is now in `soma-io/cartobase`, thus this file should rather be directly in `soma-io`. I'm fixing that.
