### ISSUE TITLE
alignment problem in AimsFFDApply in nearest neighbor mode

### ISSUE THREAD

**Issue by denisri** [brainvisa/aims-free#6]
---

Author Name: **Riviere, Denis** (@denisri)
Original Redmine Issue: 12497, https://bioproj.extra.cea.fr/redmine/issues/12497
Original Date: 2015-05-07
Original Assignee: Souedet, Nicolas

---

There seems to be a shift in the diagonal direction, possibly the classical "half voxel", when using AimsFFDApply in nearest neighbor mode (-t n). In cubic resampling mode, the alignment is OK.

**Comment by ylep** [comment]
This is probably fixed for a long time, I did not notice any such error during the heavy lifting of FFD transformations that I did during summer 2018.
