### ISSUE TITLE
Reading and converting SVG file with AIMS without any interpolation

### ISSUE THREAD

**Issue by Sebastien-PILUSO** [brainvisa/aims-free#60]
When reading or converting a SVG file with AIMS to analyse it, an interpolation is applied on the converted resulting image. As the SVG data contains labels, I would like to avoid this interpolation.
I applied an _AimsFileConvert_ command on it to convert this file onto the GIS format.
And an interpolation between graylevels appears (see zoom in the attached image).
I have tried with other image processing libraries (pyvips, svglib) but the result is the same: the convertion comes with an interpolation.

Can somebody help me to find a way to avoid this interpoaltion to get the exact native label values on the wanted format?
Many thanks in advance.

I can't attach a SVG file here, so it is possible to directly download a 2D slice from the ALLEN Mouse Brain Atlas at this link: http://atlas.brain-map.org/atlas?atlas=1&plate=100960324#atlas=1&plate=100960324&resolution=7.35&x=4872.075880619518&y=3791.9210333573196&zoom=-2
Otherwise you also can ask me to send you such an image.

![Capture du 2021-06-28 18-41-32](https://user-images.githubusercontent.com/63786997/123673345-a56fb480-d840-11eb-97a7-460be6a0a2ea.png)

**Comment by denisri** [comment]
The SVG format is read through the Qt library and I'm not sure it is fully supported. The interpolation parameters are handled internally in Qt and I'm not sure we can really change them.
In the Allen mouse brain link you provide I only see a download option in Jpeg format (in the menu up right), I son't see how do download a SVG file.
Maybe you can try using software like Inkscape, but even there I don't know if you can change interpolation parameters.

**Comment by Sebastien-PILUSO** [comment]
Many thanks for your answer.
Sorry I gave you a wrong link towards the ALLEN Mouse Brain Interface.

Here is the link to the ALLEN data portal, where it is described how to download the data:
http://help.brain-map.org/display/api/Atlas+Drawings+and+Ontologies

The mouse brain atlas reference I would like to use is **602630314**.

The main advantage of using SVG files is the possibility to manage the vectorial objects efficiently, such as deleting region boundaries for instance. The final purpose is to perform dice calculation thanks to this atlas, so to get it in an AIMS readable format, without any boundaries, and with colors corresponding to ALLEN Mouse Brain region nomenclature.

**Comment by sapetnioc** [comment]
What should we do with this issue ?

**Comment by denisri** [comment]
There is not much we can do about it: SVG is read through an opaque intermediate layer (Qt) which we can't change, and anyway SVG as a vectorial format is not well read in a bitmap data container such as a Volume. External conversions should be considered for that, if needed.
