### ISSUE TITLE
Drop CARTO_USE_BLITZ

### ISSUE THREAD

**Issue by ylep** [brainvisa/aims-free#68]
Blitz++ is now a required dependency (see https://github.com/brainvisa/aims-free/pull/67), so we can drop support for non-Blitz builds and the `CARTO_USE_BLITZ` symbol.

**Comment by sapetnioc** [comment]
Once the corresponding PR is accepted, three references to `CARTO_USE_BLITZ` can be removed from brainvisa-cmake and anatomist-free.
