### ISSUE TITLE
AimsFlip should modify the header transformations

### ISSUE THREAD

**Issue by ylep** [brainvisa/aims-free#97]
**Describe the bug**
When AimsFlip is used to change the axes of a Volume, it currently does not care about the transformation matrices in the header, so this results in the old matrices being used with the new, flipped array. In effect, this means that in the target space (e.g. scanner-based referential) the volume is rotated/flipped around the center of the origin voxel (rightmost, anteriormost, superiormost voxel).

I believe that it would be more useful to preserve the origin of the target referential (e.g. scanner-based) so that the dataset appears to rotate about the center (e.g. isocenter of the scanner).

I could go ahead and try to implement this change, but considering the current work of @denisri on arbitrary volume orientation, I believe it is better to discuss it first, and maybe wait for these new APIs to be in place.

**Environment:**
 - Engine: Singularity
 - Version of BrainVISA : 5.1.1 & master

**Comment by denisri** [comment]
AimsFlip is a very old command indeed, and has probably not be updated with transformations modifications like in AimsApplyTransform.
Yes I'm working on arbitrary volume orientation these days so we could more easily update this command after this work is done.

**Comment by denisri** [comment]
Modifications have been implemented as I have proposed: options `-n` and `-c` have been added, and the default adapts transformations so that data do not move in other referentials (the volume referential changes) as in `AimsApplyTransform`.
Tell me if it is correct for you, @ylep.

**Comment by ylep** [comment]
Thanks a lot @denisri, I think this is a very sensible new default! Actually my use-case will benefit from the new `--center` option (for keeping the reference to the magnet isocenter while correcting for the anatomical orientation of the specimen).
