### ISSUE TITLE
Compilation error with gcc 12.2.0

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/aims-free#99]
**Describe the bug**
While testing a compilation within an environment setup with Conda (using conda-forge repository), I have a compilation error that may be due to a change in gcc. 

**To Reproduce**

Well, one have to create a complete Conda environment and to start a compilation. The recipe to setup the environment from scratch (AppTainer required) will be [in this project](https://github.com/sapetnioc/brainvisa-submodules). At the time of this writing it has to be changed to get rid of the use of git submodule.

Here is the compilation error:

```
/casa/build/include/aims/distancemap/meshdistance_d.h:210:23: error: redefinition of default argument for 'class MapType'
  210 | template <typename T, typename MapType=std::vector< std::map<size_t, float> > >
      |                       ^~~~~~~~
/casa/build/include/aims/distancemap/meshdistance.h:78:15: note: original definition appeared here
   78 |               typename MapType=std::vector< std::map<size_t, float> > >
      |               ^~~~~~~~
make[2]: *** [build_files/aims-free/aimsalgo/src/aimsalgo/CMakeFiles/aimsalgo.dir/build.make:356: build_files/aims-free/aimsalgo/src/aimsalgo/CMakeFiles/aimsalgo.dir/distancemap/meshdistance.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:22743: build_files/aims-free/aimsalgo/src/aimsalgo/CMakeFiles/aimsalgo.dir/all] Error 2
```
 
**Expected behavior**
A compilation without error.

**Additional context**
```
Apptainer> g++ --version
g++ (conda-forge gcc 12.2.0-19) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by denisri** [comment]
I think it is because a template argument has a default value, and the default is repeated in the the implementation. This has possibly become illegal (like function arguments).
I have pushed a fix, can you try it again please ?

**Comment by sapetnioc** [comment]
Great, thanks Denis. Compilation is still ongoing but I saw some Aims commands so I think it is ok.
